create table application
(
    actif       boolean      not null,
    id          bigint generated by default as identity
        primary key,
    code        varchar(50)  not null
        unique,
    libelle     varchar(100) not null,
    description varchar(255)
);

alter table application
    owner to manar;

create table environment_type
(
    actif   boolean     not null,
    id      bigint generated by default as identity
        primary key,
    code    varchar(50) not null
        unique,
    libelle varchar(100)
);

alter table environment_type
    owner to manar;

create table profil
(
    actif             boolean      not null,
    admin             boolean      not null,
    is_deleted        boolean      not null,
    id                bigint generated by default as identity
        primary key,
    code              varchar(50)  not null
        unique,
    keycloak_group_id varchar(100),
    libelle           varchar(100) not null,
    description       varchar(255)
);

alter table profil
    owner to manar;

create table projet
(
    actif         boolean      not null,
    id            bigint generated by default as identity
        primary key,
    code          varchar(100) not null
        unique,
    libelle       varchar(150),
    description   varchar(255),
    env_type_code varchar(50)
);

alter table projet
    owner to manar;

create table environnement
(
    actif       boolean      not null,
    id          bigint generated by default as identity
        primary key,
    projet_id   bigint       not null
        constraint fkm0185goqi60nepaastmmjwrmj
            references projet,
    type_id     bigint       not null
        constraint fkhqmssa4khd1l514q497dhh355
            references environment_type,
    code        varchar(50)  not null,
    libelle     varchar(100) not null,
    description varchar(255)
);

alter table environnement
    owner to manar;

create table env_application
(
    actif                   boolean not null,
    port                    integer,
    app_id                  bigint  not null
        constraint fk6rl0wfx9w09i96shlwg69eh43
            references application,
    date_derniere_livraison timestamp(6),
    env_id                  bigint  not null
        constraint fkf3b4e2cj43voueqg1p017q3c2
            references environnement,
    id                      bigint generated by default as identity
        primary key,
    description             varchar(255),
    host                    varchar(255),
    password                varchar(255),
    protocole               varchar(255),
    url                     varchar(255),
    username                varchar(255)
);

alter table env_application
    owner to manar;

create table role
(
    actif     boolean      not null,
    env_id    bigint
        constraint fk7msfsxbotsq2x2mtrcurcispy
            references environnement,
    id        bigint generated by default as identity
        primary key,
    projet_id bigint
        constraint fkbg4uid81vx00k50swk3ytclqa
            references projet,
    action    varchar(20)  not null
        constraint role_action_check
            check ((action)::text = ANY
        ((ARRAY ['CONSULT'::character varying, 'CREATE'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying])::text[])),
    scope     varchar(20)
        constraint role_scope_check
            check ((scope)::text = ANY
                   ((ARRAY ['ENV_TYPE'::character varying, 'PROJECT'::character varying, 'MENU'::character varying, 'SYSTEM'::character varying])::text[])),
    code      varchar(100) not null
        unique,
    libelle   varchar(150)
);

alter table role
    owner to manar;

create table profil_role
(
    id        bigint generated by default as identity
        primary key,
    profil_id bigint not null
        constraint fkdb8tyfhu61c6j04dqpu7cbgyq
            references profil,
    role_id   bigint not null
        constraint fk8etkmhwd1pw2unbwycarjsw0d
            references role
);

alter table profil_role
    owner to manar;

create table utilisateur
(
    actif       boolean      not null,
    is_deleted  boolean      not null,
    id          bigint generated by default as identity
        primary key,
    profil_id   bigint       not null
        constraint fkssvnc79lcj8l1hwgm230fiuh7
            references profil,
    code        varchar(100) not null
        unique,
    first_name  varchar(100),
    last_name   varchar(100),
    email       varchar(150),
    keycloak_id varchar(150)
);

alter table utilisateur
    owner to manar;

create table projet_env_type
(
    projet_id   bigint not null
        constraint fk54b4k1x0mvwu3e2re31oyneqq
            references projet,
    env_type_id bigint not null
        constraint fks06po7j6f1w215cq7o7k3k6tx
            references environment_type,
    primary key (projet_id, env_type_id)
);

alter table projet_env_type
    owner to manar;

create index idx_pet_env
    on projet_env_type (env_type_id);

--------------------------------------------------------------------------------------
